name: Build

on:
  push:
    branches:
    - 'master'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        run: swift build
  generate-from-proto:
    name: generate from protos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install tools
        run: pip3 install protoc-gen-mavsdk && brew install protobuf
      - name: generate from protos
        run: bash Sources/MAVSDK-Swift/tools/generate_from_protos.bash
      - name: check for diff
        run: git diff --exit-code
  generate-docs:
    name: generate documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install tools
        run: gem install jazzy && pip install s3cmd
      - name: generate docs
        run: bash Sources/MAVSDK-Swift/tools/generate_docs.sh
      - name: deploy docs (if master)
        if: github.ref == 'refs/heads/master')
        run: s3cmd --acl-public --access_key=${{ secrets.AWS_ACCESS_KEY_ID }} --secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} --add-header="Cache-Control:public, max-age=0" put --recursive docs/swift_output/* s3://dronecode-sdk-swift/docs/master/;
      - name: deploy docs (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: s3cmd --acl-public --access_key=${{ secrets.AWS_ACCESS_KEY_ID }} --secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} --add-header="Cache-Control:public, max-age=0" put --recursive docs/swift_output/* s3://dronecode-sdk-swift/docs/${GITHUB_REF#refs/tags/}/;
