name: Build

on:
  push:
    branches:
    - 'master'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        run: swift build
  generate-from-proto:
    name: generate from protos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install tools
        run: pip3 install protoc-gen-mavsdk && brew install protobuf
      - name: generate from protos
        run: bash Sources/MAVSDK-Swift/tools/generate_from_protos.bash
      - name: check for diff
        run: git diff --exit-code
  generate-docs:
    name: generate documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install tools
        run: gem install jazzy
      - name: generate docs
        run: bash Sources/MAVSDK-Swift/tools/generate_docs.sh
